project:
  type: website
  output-dir: docs
  

website:
  title: "Kate Becker"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: resources2.qmd
        text: Resources

format:
  html:
    theme: 
      light: minty
      dark: darkly
    css: styles.css
    toc: true
    page-layout: full

editor: source

