project:
  type: website
  output-dir: docs
  

website:
  navbar:
    title: "Kate A. Becker"
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: Resume_CV/ShakaResumeNew.pdf
        text: Resume 
      - posts.qmd
    right: 
    - text: LinkedIn
      href: https://www.linkedin.com/in/kate-becker-b3163a193/
      icon: linkedin
    - text : GitHub
      icon : github
      href : https://github.com/kateebeckerr
    - text: Email
      href: mailto:katebecker06@gmail.com
      icon: inbox
  page-footer: 
    background: light 
    left: "Copyright 2024, Kate Becker"
    right: 
      - icon: github
        href: https://github.com/kateebeckerr
      
format:
  html:
    theme: 
      - styles.scss
    mainfont: Roboto
    toc: true
    page-layout: full

editor: source
